/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  SearchableWordsModal: () => SearchableWordsModal,
  default: () => WordyPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// DatamuseApi.ts
var DatamuseApi = class {
  constructor() {
    this.baseUrl = new URL("https://api.datamuse.com/words");
  }
  async wordsSimilarTo(rootWord) {
    const similarWords = {
      relatedWords: []
    };
    const urls = ["rel_syn", "rel_spc", "rel_gen", "rel_com", "rel_par"];
    await Promise.all(urls.map(async (queryParam) => {
      const url = `${this.baseUrl}?${queryParam}=${rootWord}`;
      const resp = await fetch(url);
      const data = await resp.json();
      similarWords.relatedWords.push(...data.map((o) => o.word));
    }));
    return similarWords;
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  enumeratedWords: true
};
var WordyPlugin = class extends import_obsidian.Plugin {
  constructor(app, manifest) {
    super(app, manifest);
    this.datamuseApi = new DatamuseApi();
  }
  async onload() {
    await this.loadSettings();
    this.addCommand({
      id: "wordy-syn",
      name: "Synonyms",
      editorCallback: async (editor, view) => {
        const rootWord = editor.getSelection();
        if (rootWord != "") {
          const similarWords = await this.datamuseApi.wordsSimilarTo(rootWord);
          if (similarWords.relatedWords.length == 0) {
            new import_obsidian.Notice(`Oops \u2014 No synonyms found.`);
            return;
          }
          new SearchableWordsModal(this.app, similarWords.relatedWords, (selectedWord) => {
            editor.replaceSelection(selectedWord);
          }).open();
        } else {
          new import_obsidian.Notice(`Oops \u2014 Select a word first.`);
        }
      }
    });
    this.addSettingTab(new WordyPluginSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var SearchableWordsModal = class extends import_obsidian.SuggestModal {
  constructor(app, words, replaceFn) {
    super(app);
    this.words = words;
    this.replaceFn = replaceFn;
    if (words.length == 0) {
      return;
    }
  }
  getSuggestions(query) {
    return this.words.filter((word) => word.toLowerCase().includes(query.toLowerCase()));
  }
  renderSuggestion(word, el) {
    el.createEl("div", { text: word });
  }
  onChooseSuggestion(word, evt) {
    this.replaceFn(word);
  }
};
var WordyPluginSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Settings" });
    containerEl.createEl("p").setText("Nothing to configure yet!");
  }
};
